
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE             0
#define PARTNER_SIERRA           1
#define PARTNER_MAY_CHESPIN      2
#define PARTNER_MAY_TEPIG        3
#define PARTNER_MAY_SOBBLE       4
#define PARTNER_BRENDAN_CHESPIN  5
#define PARTNER_BRENDAN_TEPIG    6
#define PARTNER_BRENDAN_SOBBLE   7
#define PARTNER_STEVEN           8
#define PARTNER_COUNT            9

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
