#ifndef GUARD_ITEM_CONSTANTS_H
#define GUARD_ITEM_CONSTANTS_H

#include "config/frlg_bag.h"

enum Pocket
{
    POCKET_ITEMS,
    POCKET_POKE_BALLS,
#if FRLG_I_ADD_TM_CASE_WITH_TMS != TRUE
    POCKET_TM_HM,
#endif
#if FRLG_I_ADD_BERRY_POUCH_WITH_BERRIES != TRUE
    POCKET_BERRIES,
#endif
    POCKET_KEY_ITEMS,
#if FRLG_I_ADD_TM_CASE_WITH_TMS == TRUE
    POCKET_TM_HM,
#endif
#if FRLG_I_ADD_BERRY_POUCH_WITH_BERRIES == TRUE
    POCKET_BERRIES,
#endif
    POCKETS_COUNT,
    POCKET_DUMMY = POCKETS_COUNT,
    POCKET_MAX_SCROLL = POCKET_KEY_ITEMS,
};

#define REPEL_LURE_MASK         (1 << 15)
#define IS_LAST_USED_LURE(var)  (var & REPEL_LURE_MASK)
#define REPEL_LURE_STEPS(var)   (var & (REPEL_LURE_MASK - 1))
#define LURE_STEP_COUNT         (IS_LAST_USED_LURE(VarGet(VAR_REPEL_STEP_COUNT)) ? REPEL_LURE_STEPS(VarGet(VAR_REPEL_STEP_COUNT)) : 0)
#define REPEL_STEP_COUNT        (!IS_LAST_USED_LURE(VarGet(VAR_REPEL_STEP_COUNT)) ? REPEL_LURE_STEPS(VarGet(VAR_REPEL_STEP_COUNT)) : 0)

#define ITEM_SELL_FACTOR ((I_SELL_VALUE_FRACTION >= GEN_9) ? 4 : 2)

#endif // GUARD_ITEM_CONSTANTS_H
